name: factoryio_app
description: "Mqtt client for FactoryIO"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.0

dependencies:
  dynamic_color: ^1.7.0
  file_picker: ^10.0.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  mqtt_client: ^10.8.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true